{% set name = "pytraj" %}
{% set version = "2.0.4" %} # 

package:
  name: {{ name }}
  version: !!str {{ version }}

requirements:
  build:
    - python
    - libnetcdf
  run:
    - python
    - libnetcdf
    - numpy

test:
  commands:
    - python -c 'import pytraj as pt; pt.show_versions(); from pytraj.testing import get_remd_fn'

about:
  home: http://github.com/amber-md/pytraj
  license: GPL v3
  summary: Python API for cpptraj - a package for data analysis of MD simulations
