python3 ./test_cast_dataset.py 
python3 ./test_rmsd.py 
python3 ./test_Action_Matrix.py 
python3 ./test_get_remdtraj.py 
python3 ./test_DataSet_integer.py 
python3 ./test_Box.py 
python3 ./test_io_save_indices.py 
python3 ./test_teasing_traj.py 
python3 ./test_TrajReadOnly_iter.py 
python3 ./test_DataSet_float.py 
python3 ./test_load_data_sample.py 
python3 ./test_Frame_6.py 
python3 ./test_DataSet_double.py 
python3 ./test_Action_Rotate.py 
python3 ./test_NameType.py 
python3 ./test_Trajin_Single.py 
python3 ./test_FrameArray.py 
python3 ./test_save_trajlist.py 
python3 ./test_misc.py 
python3 ./test_Action_Surf.py 
python3 ./test_adict.py 
python3 ./test_randomize_ions.py 
python3 ./test_Frame_5.py 
python3 ./test_netcdf.py 
python3 ./test_FrameArray_extensive_indexing.py 
python3 ./test_io.py 
python3 ./test_FrameArray_atommask.py 
python3 ./test_fancy_indexing_2.py 
python3 ./test_CpptrajFile.py 
python3 ./test_template.py 
python3 ./test_Action_DSSP.py 
python3 ./test_simple_Topology.py 
python3 ./test_get_subframe.py 
python3 ./test_fancy_indexing.py 
python3 ./test_Residue.py 
python3 ./test_CpptrajState.py 
python3 ./test_Action_Radgyr.py 
python3 ./test_math.py 
python3 ./test_python33.py 
python3 ./test_ActionList_2.py 
python3 ./test_MolSurf.py 
python3 ./test_listIndex_FrameArray.py 
python3 ./test_Action_PairDist.py 
python3 ./test_FrameArray_2.py 
python3 ./test_TMscore.py 
python3 ./test_Topology_2.py 
python3 ./test_TrajReadOnlyTest.py 
python3 ./test_FrameArray_save.py 
python3 ./test_allactions_allanalyses_doc.py 
python3 ./test_analysisdict.py 
python3 ./test_Topology.py 
python3 ./test_FrameArray_append.py 
python3 ./test_TrajectoryFile.py 
python3 ./test_remd_0.py 
python3 ./test_ActionDict.py 
python3 ./test_ParmFile.py 
python3 ./test_ActionList_Image.py 
python3 ./test_TrajReadOnly.py 
python3 ./test_AtomMask.py 
python3 ./test_load_indices.py 
python3 ./test_randomize_ions_2.py 
python3 ./test_load_CHARMM.py 
python3 ./test_version.py 
python3 ./test_Trajout.py 
python3 ./test_Vec3.py 
python3 ./test_GridAction.py 
python3 ./test_Action_Checkchirality.py 
python3 ./test_DataSet_string.py 
python3 ./test_ActionList.py 
python3 ./test_watershell.py 
python3 ./test_DistRoutines.py 
python3 ./test_Action_Image.py 
python3 ./test_memview3D.py 
python3 ./test_iter_Traj.py 
python3 ./test_writepdb.py 
python3 ./test_AtomSelect.py 
python3 ./test_Action_Jcoupling.py 
python3 ./test_indexing_speed.py 
python3 ./test_known_bugs.py 
python3 ./test_Frame_iter.py 
python3 ./test_DataSet_Coords_TRJ.py 
python3 ./test_Frame_box.py 
python3 ./test_calculate_from_misc.py 
python3 ./test_DataSet_Coords_CRD.py 
python3 ./test_Matrix_3x3.py 
python3 ./test_GDTscore.py 
python3 ./test_FrameArray_help.py 
python3 ./test_alias_for_actions.py 
python3 ./test_Frame_3.py 
python3 ./test_dummy_indexing_FrameArray.py 
python3 ./test_Topology_build.py 
python3 ./test_Action_Distance.py 
python3 ./test_Frame_4.py 
python3 ./test_TopologyList.py 
python3 ./test_DataSetList.py 
python3 ./test_hd5f.py 
python3 ./test_loadpdb_rcsb.py 
python3 ./test_mdtraj_to_pycpptraj_top.py 
python3 ./test_Atom.py 
python3 ./test_Trajin.py 
python3 ./test_Frame_1.py 
python3 ./test_TrajinList.py 
python3 ./test_FrameArray2.py 
python3 ./test_base.py 
python3 ./test_Action_Strip.py 
python3 ./test_fancy_indexing_simple_test.py 
python3 ./test_loadingtime.py 
python3 ./test_Frame_2.py 
python3 ./test_has_numpy.py 
python3 ./test_Atom_2.py 
