{% set name = "libcpptraj-dev" %}

# original cpptraj internal version: '4.3.2'
# add '.1' to the end for each pytraj release
{% set version = os.getenv('VERSION', '4.3.2.1') %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/amber-md/cpptraj.git
  git_tag: master

requirements:
  build:
    - zlib
    - bzip2
    - libnetcdf
    - openblas [linux]
    - libgfortran [linux]
    - gcc [linux]
  run:
    - zlib
    - bzip2
    - libnetcdf
    - openblas [linux]
    - libgfortran [linux]
    - gcc [linux]

about:
    home: https://github.com/amber-md/cpptraj/
    license: GPL v3
    summary: Biomolecular simulation trajectory/data analysis. 
