#!/usr/bin/env python

import os
import sys

cwd = os.getcwd()

try:
    sys.argv.remove('--amber')
    ambertools_distro = True
except ValueError:
    ambertools_distro = False

if ambertools_distro:
    pytraj_dir = os.path.abspath('./AmberTools/src/pytraj/')
else:
    pytraj_dir = './'

os.chdir(pytraj_dir)

os.system('git clean -fdx .')

# change to release status 
with open('scripts/base_setup.py', 'r') as fh:
    old_content = fh.read()
    new_content = old_content.replace('is_released = False', 'is_released = True') 

with open('scripts/tmp.py', 'w') as fh:
    fh.write(new_content)

os.system('mv scripts/tmp.py scripts/base_setup.py')
os.system('python scripts/cythonize.py')

if not ambertools_distro:
    # upload to pip
    os.system('python setup.py sdist')
    # restore to ISRELEASED = False
    os.system('git checkout scripts/base_setup.py')

os.chdir(cwd)
