"""some common symbols
see also: http://matplotlib.org/users/mathtext.html
"""

alpha_ = r"$\alpha$"
beta_ = r"$\beta$"
gamma_ = r"$\gamma$"
chi_ = r"$\chi$"
delta_ = r"$\delta"
phi_ = r"$\phi$"
psi_ = r"$\psi$"
tau_ = r"$\tau$"
rho_ = r"$\rho$"
theta_ = r"$\theta$"
zeta_ = r"$\zeta$"
lambda_ = r"$\lambda$"
angstrom_ = r"$\AA$"
microsecond_ = r"$\mu$s"
sum_ = r"$\sum$"
kappa_ = r"\kappa"
mu_ = r"\mu"
nu_ = r"\nu"
pi_ = r"\pi"
