#ifndef CPPTRAJ_VERSION_STRING
#define CPPTRAJ_VERSION_STRING "V15.22b"
#endif
#ifndef NETCDF_VERSION_STRING
#define NETCDF_VERSION_STRING "V14.0"
#define NETCDF_VERSION_STRLEN 5
#endif
#ifndef CPPTRAJ_INTERNAL_VERSION
#define CPPTRAJ_INTERNAL_VERSION "V4.1.5"
#endif
