package:
  name: libcpptraj
  version: 4.2.4

source:
  git_url: https://github.com/amber-md/cpptraj.git
  git_tag: master

requirements:
  build:
    - libnetcdf
    - zlib
    - bzip2
  run:
    - libnetcdf
    - zlib
    - bzip2

about:
    home: http://ambermd.org/
    license: GNU
    summary: libcpptraj for pytraj
