# this file was auto-generated by scripts/find_action_and_analysis_commands.py
action_commands = (
    'angle', 'areapermol', 'atomiccorr', 'atomicfluct', 'atommap', 'autoimage',
    'average', 'bounds', 'box', 'center', 'channel', 'check', 'checkchirality',
    'checkoverlap', 'checkstructure', 'closest', 'closestwaters',
    'clusterdihedral', 'contacts', 'createcrd', 'createreservoir', 'density',
    'diffusion', 'dihedral', 'dihedralscan', 'dipole', 'distance', 'drms',
    'drmsd', 'dssp', 'energy', 'filter', 'fixatomorder', 'gist', 'grid',
    'hbond', 'image', 'jcoupling', 'lessplit', 'lie', 'lipidorder',
    'makestructure', 'mask', 'matrix', 'minimage', 'molsurf', 'multidihedral',
    'multivector', 'nastruct', 'nativecontacts', 'nmrrst', 'outtraj',
    'pairdist', 'pairwise', 'principal', 'projection', 'pucker', 'radgyr',
    'radial', 'randomizeions', 'rdf', 'replicatecell', 'rms', 'rmsd', 'rmsf',
    'rog', 'rotate', 'runavg', 'runningaverage', 'scale', 'secstruct',
    'setvelocity', 'spam', 'stfcdiffusion', 'strip', 'surf', 'symmrmsd',
    'temperature', 'trans', 'translate', 'unstrip', 'unwrap', 'vector',
    'velocityautocorr', 'volmap', 'volume', 'watershell')

analysis_commands = (
    '2drms', 'amdbias', 'autocorr', 'avg', 'calcstate', 'cluster', 'corr',
    'correlationcoe', 'crank', 'crankshaft', 'crdfluct', 'crosscorr',
    'curvefit', 'diagmatrix', 'divergence', 'fft', 'hist', 'histogram',
    'integrate', 'ired', 'kde', 'lifetime', 'lowestcurve', 'matrix',
    'meltcurve', 'modes', 'multicurve', 'multihist', 'overlap', 'phipsi',
    'regress', 'remlog', 'rms2d', 'rmsavgcorr', 'rotdif', 'runningavg',
    'spline', 'stat', 'statistics', 'ti', 'timecorr', 'vectormath', 'wavelet')
